### ISSUE TITLE
Peer review for Claire's paper

### ISSUE THREAD

**Issue by zzq20010617** [ClaireUoft/Toronto_TTC_Delay#1]
Summary
The paper from Claire is not updated yet, but from the part she has done like the scripts, simulation, and model setup in the paper, we can get the idea of analyzing the relationship between time of delay and factors like type of transportation, time of the day, etc. Everything(especially scripts and sketches) except the paper is done well, the topic is closely connected to our life and I'm looking forward to seeing the result. Remember to include Surveys, sampling, and observational data section in the appendix and one Enhancement technique as the rubric requires.

No marks for now cause the paper is incomplete.

**Comment by ClaireUoft** [comment]
Thanks!
