### ISSUE TITLE
Peer Review#2 - Yun Chu

### ISSUE THREAD

**Issue by chuyun2024** [ClaireUoft/Toronto_TTC_Delay#3]
Summary
The paper investigates the frequency and duration of delays across different TTC.

Strong positive points:

- README gives an excellent summary of the paper.
- download data instruction is very clear and is step-by-step.

Critical improvements needed:

- Paper content needs to be added.

Suggestions for improvement:

- add introduction
- add data
- add model
- add result
- add discussion

Evaluation: 
R/Python cited (0/1 pts)
since paper is not written yet
Data cited (0/1 pts)
Class paper (1/1 pts)
LLM documentation (0/1 pts)
Title (2/2 pts)
using both title and subtitle
Author, date, and repo (2/2 pts)
Abstract (0/4 pts)
Introduction (0/4 pts)
Estimand (0/1 pts)
Data (0/10 pts)
Measurement (0/4 pts)
Model (0/10 pts)
Results (0/10 pts)
Discussion (0/10 pts)
Prose (0/6 pts)
Cross-reference(0/1 pts)
Captions (0/2 pts)
Graphs/tables/etc (0/4 pts)
Surveys, sampling, and observational data appendix (0/10 pts)
this section is not present
Referencing (0/4 pts)
Commits (2/2 pts)
Sketches (2/2 pts)
Simulation (4/4 pts)
Tests (4/4 pts)
Parquet (1/1 pts)
Reproducible workflow (4/4 pts)
Enhancements (0/4 pts)
Miscellaneous (0/3 pts)
Estimated overall mark:
[22] out of [112].
Any other comments: Great work so far! Good luck with you paper writing :)

**Comment by ClaireUoft** [comment]
Thank you!
